language: c
env:
  global:
    - CONDA_PYTHON_DEPENDENCIES="atlas numpy scipy matplotlib coverage pyflakes"
    - EXTERN_PAYTHON_DEPENDENCIES="-c https://conda.anaconda.org/chemreac/channel/main python-coveralls"
  matrix:
    - PYTHON_VERSION="3.3"
    - PYTHON_VERSION="3.4"
    - PYTHON_VERSION="3.5"

#use container based infrastructure
sudo: false

#these directories are persistent
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/clean_miniconda3

# Setup anaconda
before_install:
# install miniconda with symlink of pkg dir to cache
  - chmod +x ./install_miniconda3.sh
  - ./install_miniconda3.sh
#
  - export PATH=$HOME/miniconda3/bin:$PATH
install:
  - python setup.py install
script:
  - "coverage run --source=src --rcfile=coverage.ini setup.py test"
after_success:
    - coveralls

