language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

#use container based infrastructure
sudo: false

#these directories are persistent
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/miniconda3_pkgs
    - $HOME/Downloads

# Setup anaconda
before_install:
# install miniconda with symlink of pkg dir to cache
  - chmod +x ./install_miniconda3.sh
  - ./install_miniconda3.sh
#
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy matplotlib
  - pip install pyflakes coverage coveralls
install:
  - python setup.py install
script:
  - "coverage run --source=src --rcfile=coverage.ini setup.py test"
after_success:
    - coveralls

